= Roboquant Docker image

The roboquant docker image includes the following software:
- Jupyter notebook image (`jupyter/base-notebook`) as the base image
- Kotlin kernel for Jupyter
- OpenJDK 11 runtime
- Roboquant tutorials and test data

== Usage
You can start using Jupyter Lab straight out-of-the-box by running the following command:

[source,bash]
----
docker run --rm -p 8888:8888 roboquant/jupyter
----

or if you like the classic Jupyter-Notebook environment better:

[source,bash]
----
docker run --rm -p 8888:8888 -e JUPYTER_ENABLE_LAB="" roboquant/jupyter
----

Then open the url that appears in your terminal in your browser to try it out. The `tutorials` directory contains several notebooks that provide a nice introduction into roboquant.


== Build Docker Image
You can also build the Docker image from the source. First thing to do is to clone the roboquant-notebook GitHub repository to your local disk. Then run the build script from the repository root directory:

[source,shell]
----
./docker/dockerbuild.sh
----

The build script has been tested and used with Docker Desktop. It builds by default both an image for both Intel and ARM64 (Apple Silicon). See the script if you didn't enable the new builder yet.

Right now only shell scripts are provided to build and start notebooks. So if you're on Windows you either have to use WSL or run the commands in the shell script from the command line manually.
